name: Build Backend

on:
  workflow_call:
    inputs:
      SONAR_TOKEN:
        required: true
        type: string
      SONAR_HOST_URL:
        required: true
        type: string
      GITHUB_TOKEN:
        required: true
        type: string
      RUNNER_OS:
        required: true
        type: string

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: SonarPhase
        uses: ./.github/workflows/mvn-sonar
        with: 
          SONAR_TOKEN: ${{ SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
          RUNNER_OS: ${{ RUNNER_OS }}
          MODULE: hunger-games-backend
          JDK_VERSION: 17
