name: Build Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./hunger-games-backend/**
    

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-backend
