name: Build All

on: 
  workflow_dispatch: 
    

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-backend
  build-discord-gw:
    name: Build Discord Gateway
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-discord-gw
    
